### ISSUE TITLE
Readme.md explain better please

### ISSUE THREAD

**Issue by Pactivism** [mickdevill/Entrevoisins#1]
Можете ли вы объяснить, что это приложение делает чуть более подробно, пожалуйста ? 
Заранее спасибо ! @mickdevill

**Comment by mickdevill** [comment]
https://s3-eu-west-1.amazonaws.com/course.oc-static.com/projects/GEN+android+P4/Note+de+cadrage+-+Mare%CC%81u.pdf

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

сб, 25 июл. 2020 г. в 19:21, Pactivism <notifications@github.com>:
